import { Link, Route, Routes } from "react-router-dom";

import { CollectionList } from "./components/CollectionList";
import { CollectionView } from "./components/CollectionView";
import { ItemDetail } from "./components/ItemDetail";
import { ItemForm } from "./components/ItemForm";

function NotFound() {
  return (
    <>
      <h1>Not found</h1>
      <p className="muted">
        <Link to="/">Back to collections</Link>
      </p>
    </>
  );
}

export function App() {
  return (
    <>
      <header className="site-header">
        <Link className="brand" to="/">
          Collections
        </Link>
        <span className="tagline">Schema-first collections</span>
      </header>

      <main className="app">
        <Routes>
          <Route path="/" element={<CollectionList />} />
          <Route path="/c/:name" element={<CollectionView />} />
          <Route path="/c/:name/new" element={<ItemForm mode="create" />} />
          <Route path="/c/:name/:id" element={<ItemDetail />} />
          <Route path="/c/:name/:id/edit" element={<ItemForm mode="edit" />} />
          <Route path="*" element={<NotFound />} />
        </Routes>
      </main>

      <footer className="site-footer">
        Generated by <code>collections-ui</code>
      </footer>
    </>
  );
}
